blank_issues_enabled: false
contact_links:
  - name: Questions and discussions
    url: https://github.com/kolonaki/kolonaki/discussions
    about: Please start a discussion for usage questions or broader topics.
